# short circuit the sourcing for non-interactive shells
# http://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile
[[ $- != *i* ]] && return

# To enable debug printing, just uncomment this
# You can then use `debug` or `t_debug` statements to echo debug info
# DEBUG=yup

function read_config {
  if [ -a "$1" ]; then
      . "$1"
  else echo Missing $1
  fi
}

function read_config_if_exists {
  [ -a "$1" ] && . "$1"
}

# Needed for the utility function "restore_path"
if [ -z "${ORIGINAL_PATH}" ]; then
        ORIGINAL_PATH="${PATH}"
fi

declare -x CLICOLOR
ulimit -c unlimited
umask 022

# include selfmade binaries and scripts
# Needed for some of the utility functions
if [ -d ~/bin ] ; then
    PATH=~/bin:"${PATH}"
fi

if [ -d ~/scripts ] ; then
	PATH=~/scripts:"$PATH"
fi

# Read in utility functions (like t_debug, and timer_start)
read_config "$HOME/.bash.d/bash_functions"
read_config "$HOME/.bash.d/bash_aliases"

# For debugging info on timing
timer_start

read_config_if_exists "$HOME/.bashrc.local"

t_debug Executing '$HOME'/.bashrc

read_config "$HOME/.bash.d/git-prompt.sh"

for f in "${HOME}"/.bash_completion.d/*; do
    t_debug $f
    read_config "$f"
done

t_debug Reading color codes
read_config_if_exists "$HOME/.bash.d/color_codes.dat"


#Se man bash i delen som heter "Prompting"
user="${green}\u${X}"
host="${dark_yellow}\h${X}"
workdir="${pink}\w${X}"
gitbranch="${dark_red}\$(__git_ps1 \" (%s)\")${X}"
at="${dark_grey}at${X}"
in="${dark_grey}in${X}"
export PS1="\n${user} ${at} ${host} ${in} ${workdir} ${gitbranch}\n\$ "

# From http://stackoverflow.com/questions/9457233/unlimited-bash-history
# Eternal bash history.
# ---------------------
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

export PATH="/usr/local/bin:$PATH"
export PYTHONSTARTUP="$HOME/.pystartup"
export HISTCONTROL=ignoredups

export VISUAL='vim'
export EDITOR='vim'

t_debug Load NVM
export NVM_DIR="/Users/carl-erik.kopseng/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

t_debug Finished .bashrc

[ -s "/Users/carl-erik.kopseng/.dnx/dnvm/dnvm.sh" ] && . "/Users/carl-erik.kopseng/.dnx/dnvm/dnvm.sh" # Load dnvm
source ~/.bash_completion.d/azure
