[[search_dirs]]
path = "~/code"
depth = 3

[[search_dirs]]
path = "~/dev"
depth = 3

[shortcuts]
ctrl-k = "delete_to_line_end"
# Available actions are:
# "" (to remove a default binding)
# "cancel"
# "confirm"
# "backspace"
# "delete"
# "move_up"
# "move_down"
# "cursor_left"
# "cursor_right"
# "delete_word"
# "delete_to_line_start"
# "delete_to_line_end"
# "move_to_line_start"
# "move_to_line_end"

