# ~/.config/tms/config.toml

# Keyboard shortcuts can be customized by adding a [shortcuts] section in the config file and adding bindings as pairs of shortcut = action, for example:
[shortcuts]
"ctrl-k" = "delete_to_line_end"

# Available actions are:
# "" (to remove a default binding)
# "cancel"
# "confirm"
# "backspace"
# "delete"
# "move_up"
# "move_down"
# "cursor_left"
# "cursor_right"
# "delete_word"
# "delete_to_line_start"
# "delete_to_line_end"
# "move_to_line_start"
# "move_to_line_end"

