"" Based on tips from  VIM Revisited (after dropping Janus)
"" http://mislav.uniqpath.com/2011/12/vim-revisited/

" Changelog
" 2015-09-24 Swapped Pathogen for Vundle. Simplicity!
"            Tipped from: http://lepture.com/en/2012/vundle-vs-pathogen
set nocompatible               " be iMproved
filetype off                   " required!

source ~/.vim/vundle-config
filetype plugin indent on       " load file type plugins + indentation
" To ignore plugin indent changes, instead use:
"filetype plugin on

syntax enable
set encoding=utf-8

"" GUI
" This is a default scheme that works well
" Override in ~/vimrc.local
colorscheme darkblue
set guifont=Monaco:h14

"" check out http://superuser.com/questions/693528/vim-is-there-a-downside-to-using-space-as-your-leader-key
:let mapleader="," 
"" Don't rely on Cmd working in vim. Learn to use <leader>c<space>
"" http://stackoverflow.com/questions/9450905/how-to-bind-vim-through-tmux-to-cmd-key/9451636#9451636
"" map <D-/> <plug>NERDCommenterToggle  
set showcmd "" show leader commands
set ruler

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=4 shiftwidth=4      " a tab is four spaces 
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

set printoptions=portrait:n

"" Pasting text - toggle between paste and insert mode using F2
"" http://nvie.com/posts/how-i-boosted-my-vim/
set pastetoggle=<F2>

" Remember last position
if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif


"" File type settings
"" Set filetype text if unset
autocmd BufEnter * if &filetype == "" | setlocal ft=text | endif

" text files
autocmd Filetype text set wrap | set linebreak
autocmd Filetype markdown set wrap | set linebreak

" associate *.vss (VectorScript) with Pascal filetype
au BufRead,BufNewFile *.vss set filetype=pascal
" associate Processing files with Java
au BufRead,BufNewFile *.pde set filetype=java
" associate *.ts with TypeScript
au BufRead,BufNewFile *.ts set filetype=typescript


" Auto-reload vimrc on changes
autocmd! bufwritepost .vimrc source %

" Make vim work as a crontab editor: http://vim.wikia.com/wiki/Editing_crontab
au BufEnter /private/tmp/crontab.* setl backupcopy=yes

" Make NERDTree open automatically if no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Open/Close NerdTree with Ctrl-N, but only in Normal mode
nmap <C-n> :NERDTreeToggle<CR>


source ~/.vimrc.local
