#!/bin/bash
other_host="$1"
shift
files="$@"

if [[ -z "$other_host" || -z "$files" ]]; then
  echo "$(basename $0) <user@remote> <file1 file2 ...>"
  exit 1
fi

if [[ -z `which lzop 2> /dev/null` ]]; then
  echo "Missing lzop"
  exit 1
fi

tar c --use-compress-program=lzop "$files" | \
ssh "$other_host" tar x --use-compress-program=lzop

