#!/bin/bash
# Delete all 

if [[ x$DEBUG != x ]]; then
    PS4='$LINENO: '
    set -x
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $SCRIPT_DIR/cross-platform-utils.bashlib
DRY_RUN=1

usage(){
    echo 'git-delete-merged [--doit] <[--local] | <remote>> [<branches to skip>]'
    echo
    echo 'Example: git-delete-merged --doit origin deploy-branch,demo'
    echo
    echo 'By default, "master" and "develop" are skipped'
    echo 'Specifying core.protected-branches in your git config, or'
    echo 'listing them on the command line with commas will override this'
}

# @args: <origin|--local> branch1 branch2 branch-to-keep ...
# @returns branch1 branch2
skipped(){
    default='master,develop'
    override="$(git config --get core.protected-branches)"

    # command line args trumps git config
    if [[ x$2 != x ]]; then
        override=$2
    fi

    if [[ x$override != x ]]; then
        echo "$override" 
    else 
        echo "$default"
    fi
}

print-branches(){
    for b in $@; do
        echo "   $b"
    done
}

main(){
    if [[ $1 == "--doit" ]];then
        shift
        DRY_RUN=0
    fi

    no_branches_msg="No branches to delete"
    delete_branches_msg="Deleting the following branches"

    if [[ $1 == "--local" ]];then
        branches=$(
                    git branch --merged \
                    | sed-ere -n 's/..(.*)/\1/p' \
                    | egrep -v \
                        "$(skipped $@ | sed-ere -e 's/,/|/g' -e 's/(\w+)/^\1$/g' )" \
                    | paste -s
                )

    else 
        branches=$(
                    git branch -r --merged \
                    | grep "  $1"  \
                    | sed-ere -n 's/  \w*\/(.*)/\1/p' \
                    | egrep -v \
                        "$(skipped $@ | sed-ere -e 's/,/|/g' -e 's/(\w+)/^\1$/g' )" \
                    | paste -s
                )
        no_branches_msg="${no_branches_msg} on $1"
        delete_branches_msg="${delete_branches_msg} on $1"
    fi


    if [[ x$branches == x ]];then
        echo $no_branches_msg
        exit 1
    fi

    if [[ x$DRY_RUN == x1 ]]; then
        echo "NOT DELETING any branches. Pass --doit to go through with action."
        echo
        echo "Would have deleted the following branches:"
        print-branches $branches
        echo
        echo "Would have skipped these branches: "
        print-branches $(skipped $@ | tr ',' ' ')
    else
        echo "$delete_branches_msg"
        print-branches $branches
        echo
        echo "Pausing for 2 seconds ... Press Ctrl-C to quit"
        sleep 2

        if [[ $1 == "--local" ]];then
            git branch -d $branches
        else 
            git push --no-verify --delete $1 $branches
        fi
    fi
}

if [[ $# > 0 ]]; then
    main "$@"
else
    usage
    exit 1
fi

# vim: set ft=sh
