#!/bin/bash
# vim: set ft=sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/cross-platform-utils.bashlib

for f in $@; do 
    echo "$f : $(gzip -c $f | wc -c) bytes (versus $(size $f) bytes)"
done
