#!/usr/bin/env node
// vim: ft=javascript

const notifier = require("node-notifier");

const msg = process.argv[2];
if (typeof msg !== "string") process.exit(0);

console.log("Sender melding", msg);
notifier.notify({ message: msg, title: "Ohoi, en melding!" }, (err) => {
  if(err){ console.log(err.message);
  process.exit(1);
  }
});
