#!/bin/sh
# @author Carl-Erik Kopseng carlerik@gmail.com
MAP=/opt/TeamCity/buildAgent/work/directory.map 
DIR=$(dirname $MAP)
sed -n -e '1,3d;1,/#/{/#/!p}' $MAP | \
    awk -v pwd=$PWD '
{ 
    n       = split($0, array, "->"); 
    proj    = substr(array[1], 6)
    tcdir   = substr(array[2],2,16)
    fulldir = pwd "/" tcdir

    printf("%-35s %16s \n", proj, fulldir); 
}
'
