#!/bin/bash
# To use this script you need to have set these two env variables: $BULKSMS_ID and $BULKSMS_SECRET
# I suggest putting them in ~/.bulksms.auth and sourcing that from .bashrc
#
# Usage: sms +4712345678

if [[ $# != 2 ]]; then
    echo "Usage: sms \"+4712345678\" 'Hey, we can handle ØÆÅ!\n\nThis is EEEAZY!'"
    exit 1
fi

if [[ $(/bin/echo -n $1 | wc -c) -lt 10 ]]; then
    echo "Suspect too short phone number. Got less than 10 chars"
    exit 1
fi

source ~/.bulksms.auth

read -r -d '' DATA <<- EOM
{
    "to":   "$1",
    "from": "+4740065078" ,
    "encoding": "UNICODE",
    "body": "$2"
}
EOM

curl -v -u "$BULKSMS_ID:$BULKSMS_SECRET"  -H 'Content-Type: application/json'   https://api.bulksms.com/v1/messages --data "$DATA"
