#!/bin/bash
# To use this script you need to have set these two env variables: $BULKSMS_ID and $BULKSMS_SECRET
# I suggest putting them in ~/.bulksms.auth and sourcing that from .bashrc
#
# Usage: sms +4712345678

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ $# != 2 ]]; then
    echo "Usage: sms \"+4712345678\" 'Hey, we can handle ØÆÅ!\n\nThis is EEEAZY!'"
    exit 1
fi

if [[ $(/bin/echo -n $1 | wc -c) -lt 10 ]]; then
    echo "Suspect too short phone number. Got less than 10 chars"
    exit 1
fi

source ~/.bulksms.auth

python3 $DIR/send-sms.py --phone "$1"  --id $BULKSMS_ID --secret $BULKSMS_SECRET  --msg "$2"

