export HISTFILE=~/.zsh_history
export HISTSIZE=100000 # can't be unset, like in bash
export SAVEHIST=100000 # needed in order to save it somewhere

# Appends every command to the history file once it is executed
setopt inc_append_history
# Reloads the history whenever you use it
setopt share_history

# Keybindings, like the readline bindings
# We have VI key bindings! Screw emacs/readline :D Use insert/command mode
# http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html
# To get emacs key bindings, just do `bindkey -e`
# This is like `set -o vi` in bash, ref https://www.techrepublic.com/blog/linux-and-open-source/using-vi-key-bindings-in-bash-and-zsh/

# Re-use BASH aliases
source ~/.bash.d/bash_aliases_functions


# Zsh plugin manager (handles oh-my-zsh, etc)
# https://github.com/zplug/zplug
if [ -e ~/.zplug/init.zsh ]; then
    source ~/.zplug/init.zsh
fi

##################################################
## Based on zplug Example section
## https://github.com/zplug/zplug#example
##################################################

# Load completion library for those sweet [tab] squares
zplug "lib/completion", from:oh-my-zsh

# Never got the oh-my-zsh version to work without manual configuration, 
zplug "rupa/z", use:z.sh

# Syntax highlighting for commands, load last
zplug "zsh-users/zsh-syntax-highlighting", from:github, defer:3

# Async for zsh, used by pure
zplug "mafredri/zsh-async", from:github, defer:0
# Theme!
zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/carlerik/.sdkman"
[[ -s "/home/carlerik/.sdkman/bin/sdkman-init.sh" ]] && source "/home/carlerik/.sdkman/bin/sdkman-init.sh"
