# Maskinalias
t_debug ssh aliases
alias timbuktu='ssh carl-erik@timbuktu.kopseng.no'
alias timbuktu_lokal='ssh carl-erik@192.168.10.2'
alias ifi='ssh carlerik@vor.ifi.uio.no'
alias ntnu='ssh kopseng@login.stud.ntnu.no'

# Auto-åpne Bittorrent Sync
alias timbuktu_btsync="(sleep 2 && open http://localhost:8888)& ssh -L8888:127.0.0.1:8888 carl-erik@timbuktu.kopseng.no -N"

# Reverse SSH
# Koble seg opp mot timbuktu.kopseng.no for å la alle som kobler seg til timbuktu.kopseng.no:10001 gå direkte mot ens egen maskin
# client 1: timbuktu_reverse_tunnel
# client 2: ssh -l my-client1-user -p 10001 timbuktu.kopseng.no
# Effect: client2 => timbuktu => client1
alias timbuktu_reverse_tunnel='ssh -v -R 10001:localhost:22 timbuktu.kopseng.no -N -l carl-erik'

# Ved masse søppel etter konvertering utf8<->cp1252
alias strip-non-ascii='python -c "import sys,re;[sys.stdout.write(re.sub('\''[^\x09\x0A\x0D\x20-\x7F]'\'', '\'''\'', line)) for line in sys.stdin]"'

# Konverteringer
t_debug conversions
alias urldecode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])"'
alias htmldecode='python -c "import sys, HTMLParser;h = HTMLParser.HTMLParser();print h.unescape(sys.argv[1])"'
alias htmlencode='python3 -c "import sys, html; print(html.escape(sys.argv[1]))"'
alias html2text='python -c "import sys,html2text;sys.stdout.write(html2text.html2text(sys.stdin.read()))"'

# Use Hub if installed. Just using `hub` instead of `which hub` cuts 2 seconds of Cygwin load time
t_debug Use hub if available
if /usr/local/bin/hub help > /dev/null 2>&1; then
    alias git='hub'
fi

t_debug Use mac specifics
IGNORE=""
if ! is_mac; then
  #ignore patterns
  for i in '*~' '*.pyc'; do 
      IGNORE="$IGNORE --ignore=$i"
  done
fi

alias ls="/bin/ls $IGNORE "

t_debug small utils and aliases
# Color output - when CLICOLOR is defined, --color/-G is unneeded
alias v='ls -l'
alias clean-temp='find -E ~ -type f -and -regex ".*~$|.*-ck.js|.*.tmp" -exec rm {} \;'

# Pretty print json
alias prettify_json='python -mjson.tool'

# Indent text before sending it to Stack Overflow
alias indent4="sed -E 's/(^.*)/    \1/'"

t_debug "aliases: setting up node aliases"
# node commands - important that these are enclosed in single quotes to avoid expansion!
alias npm-exec='PATH=$(npm bin):$PATH'
alias coffee='$(npm bin)/coffee'
alias grunt='$(npm bin)/grunt'
alias gulp='$(npm bin)/gulp'
alias mocha='$(npm bin)/mocha'
alias karma='$(npm bin)/karma'
alias eslint='$(npm bin)/eslint'

t_debug "aliases: finished setting up node aliases"

t_debug webserver aliases
# webdev
alias webserver="python -m SimpleHTTPServer"
alias servers='sudo lsof -iTCP -sTCP:LISTEN -P -n'

# time
alias epoch=millis #  tool that we compile ourselves

# find external ip
alias my-ip='curl http://ipinfo.io/ip'

# SOCKS proxy
alias socks_proxy='ssh -v -D 22222 carl-erik@timbuktu.kopseng.no -N'
alias socks_proxy_all='ssh -v -D :22222 carl-erik@timbuktu.kopseng.no -N'

# Git aliases
# https://github.com/holman/dotfiles/commit/666cb053e9d27d279c4643dce1ca09c2f8b69f2e
# The -r flag to less is uses to make it work with the color escape codes
alias gd='git diff --color | sed "s/^\([^-+ ]*\)[-+ ]/\\1/" | less -r'

t_debug global aliases finished
