
# Maskinalias
alias timbuktu='ssh carl-erik@timbuktu.kopseng.no'
alias timbuktu_lokal='ssh carl-erik@192.168.10.2'
alias ifi='ssh carlerik@vor.ifi.uio.no'
alias ntnu='ssh kopseng@login.stud.ntnu.no'

# Ved masse søppel etter konvertering utf8<->cp1252
alias strip-non-ascii='python -c "import sys,re;[sys.stdout.write(re.sub('\''[^\x09\x0A\x0D\x20-\x7F]'\'', '\'''\'', line)) for line in sys.stdin]"'

# Konverteringer
alias urldecode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])"'
alias htmldecode='python -c "import sys, HTMLParser;h = HTMLParser.HTMLParser();print h.unescape(sys.argv[1])"'
alias htmlencode='python3 -c "import sys, html; print(html.escape(sys.argv[1]))"'
alias html2text='python -c "import sys,html2text;sys.stdout.write(html2text.html2text(sys.stdin.read()))"'

# Use Hub if installed
if which hub > /dev/null 2>&1; then
    alias git='hub'
fi

IGNORE=""
if ! is_mac; then
  #ignore patterns
  for i in '*~' '*.pyc'; do 
      IGNORE="$IGNORE --ignore=$i"
  done
fi

alias ls="/bin/ls $IGNORE "

# Color output - when CLICOLOR is defined, --color/-G is unneeded
alias v='ls -l'
alias dir='ls --format=vertical'
alias vdir='ls --format=long'
alias clean-temp='find -E ~ -regex ".*~$|.*-ck.js|.*.tmp" -exec rm {} \;'

# Pretty print json
alias prettify_json='python -mjson.tool'

# node commands
alias npm-exec='PATH=$(npm bin):$PATH'
alias coffee="$(npm bin)/coffee"
alias grunt="$(npm bin)/grunt"
alias gulp="$(npm bin)/gulp"
alias mocha="$(npm bin)/mocha"
alias karma="$(npm bin)/karma"
alias eslint="$(npm bin)/eslint"

# webdev
alias webserver="python -m SimpleHTTPServer"
alias servers='sudo lsof -iTCP -sTCP:LISTEN -P -n'

# time
alias epoch=millis #  tool that we compile ourselves

# find external ip
alias my-ip='curl http://ipinfo.io/ip'

# SOCKS proxy
alias socks_proxy='ssh -v -D 22222 carl-erik@timbuktu.kopseng.no -N'
alias socks_proxy_all='ssh -v -D :22222 carl-erik@timbuktu.kopseng.no -N'
