
# Maskinalias
alias timbuktu='ssh carl-erik@timbuktu.hopto.org'
alias timbuktu_lokal='ssh carl-erik@192.168.10.2'
alias ifi='ssh carlerik@vor.ifi.uio.no'
alias ntnu='ssh kopseng@login.stud.ntnu.no'

# Ved masse søppel etter konvertering utf8<->cp1252
alias strip-non-ascii='python -c "import sys,re;[sys.stdout.write(re.sub('\''[^\x09\x0A\x0D\x20-\x7F]'\'', '\'''\'', line)) for line in sys.stdin]"'

alias urldecode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])"'
alias htmldecode='python -c "import sys, HTMLParser;h = HTMLParser.HTMLParser();print h.unescape(sys.argv[1])"'
alias htmlencode='python3 -c "import sys, html; print(html.escape(sys.argv[1]))"'

# Git stuff that is hard to remember
alias g_unchanged='git update-index --assume-unchanged'
alias g_push_create_remote='git push -u <remote-name> <branch-name>'

# Use Hub if installed
if which hub > /dev/null 2>&1; then
    alias git='hub'
fi

IGNORE=""
if ! is_mac; then
  #ignore patterns
  for i in '*~' '*.pyc'; do 
      IGNORE="$IGNORE --ignore=$i"
  done
fi

alias ls="/bin/ls $IGNORE "

# Color output - when CLICOLOR is defined, --color/-G is unneeded
alias v='ls -l'
alias dir='ls --format=vertical'
alias vdir='ls --format=long'
alias clean-temp='find -E ~ -regex ".*~$|.*-ck.js|.*.tmp" -exec rm {} \;'

# Pretty print json
alias prettify_json='python -mjson.tool'

# node commands
alias npm-exec='PATH=$(npm bin):$PATH'
alias coffee='npm-exec coffee'
alias grunt='npm-exec grunt'
alias gulp='npm-exec gulp'
alias mocha='npm-exec mocha'
alias karma='npm-exec karma'

# webdev
alias webserver="python -m SimpleHTTPServer"
alias servers='sudo lsof -iTCP -sTCP:LISTEN -P -n'

# time
alias epoch='date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s"'

# SOCKS proxy
alias socks_proxy='ssh -v -D 22222 carl-erik@timbuktu.hopto.org -N'
alias socks_proxy_all='ssh -v -D :22222 carl-erik@timbuktu.hopto.org -N'
alias html2text='python -c "import sys,html2text;sys.stdout.write(html2text.html2text(sys.stdin.read()))"'
