"" Based on tips from  VIM Revisited (after dropping Janus)
"" http://mislav.uniqpath.com/2011/12/vim-revisited/

set nocompatible                " choose no compatibility with legacy vi
syntax enable
set encoding=utf-8
filetype plugin indent on       " load file type plugins + indentation

"" GUI
colorscheme darkblue
set guifont=Monaco:h14

"" check out http://superuser.com/questions/693528/vim-is-there-a-downside-to-using-space-as-your-leader-key
:let mapleader="," 
"" Don't rely on Cmd working in vim. Learn to use <leader>c<space>
"" http://stackoverflow.com/questions/9450905/how-to-bind-vim-through-tmux-to-cmd-key/9451636#9451636
"" map <D-/> <plug>NERDCommenterToggle  
set showcmd "" show leader commands
set ruler

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=4 shiftwidth=4      " a tab is four spaces 
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

set printoptions=portrait:n

"" Pasting text - toggle between paste and insert mode using F2
"" http://nvie.com/posts/how-i-boosted-my-vim/
set pastetoggle=<F2>

"" File type settings
"" Set filetype text if unset
autocmd BufEnter * if &filetype == "" | setlocal ft=text | endif

" text files
autocmd Filetype text set wrap | set linebreak

" associate *.vss (VectorScript) with Pascal filetype
au BufRead,BufNewFile *.vss set filetype=pascal
" associate Processing files with Java
au BufRead,BufNewFile *.pde set filetype=java


let g:pathogen_disabled = []
source ~/.vimrc.local

if !has("macunix")
    call add(g:pathogen_disabled, 'copy-as-rtf')
endif

execute pathogen#infect()



