function read_config {
  if [ -a "$1" ]; then
      . "$1"
  else echo Missing $1
  fi
}

function read_config_if_exists {
  [ -a "$1" ] && . "$1"
}

# Needed for the utility function "restore_path"
if [ -z "${ORIGINAL_PATH}" ]; then
        ORIGINAL_PATH="${PATH}"
fi

declare -x CLICOLOR
ulimit -c unlimited
umask 022

read_config "$HOME/.bash.d/bash_functions"
read_config "$HOME/.bash.d/bash_aliases"
read_config "$HOME/.bash.d/git-prompt.sh"
read_config "$HOME/.bash.d/git-completion.bash"
read_config "$HOME/.bash.d/npm-completion.bash"
read_config_if_exists "$HOME/.bash.d/bashrc.local"
read_config_if_exists "$HOME/.bash.d/color_codes.dat"


#Se man bash i delen som heter "Prompting"
user="${green}\u${X}"
host="${dark_yellow}\h${X}"
workdir="${pink}\w${X}"
gitbranch="${dark_red}\$(__git_ps1 \" (%s)\")${X}"
at="${dark_grey}at${X}"
in="${dark_grey}in${X}"
PS1="\n${user} ${at} ${host} ${in} ${workdir} ${gitbranch}\n\$ "


# include selfmade binaries and scripts
if [ -d ~/bin ] ; then
    PATH=~/bin:"${PATH}"
fi

if [ -d ~/scripts ] ; then
	PATH=~/scripts:"$PATH"
fi

export PATH="/usr/local/bin:$PATH"
export PYTHONSTARTUP="$HOME/.pystartup"
export HISTCONTROL=ignoredups

export NVM_DIR="/Users/carl-erik.kopseng/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
